In [1]:
import torch

In [4]:
t1 = torch.full((2,2,3),26)
t1

tensor([[[26, 26, 26],
         [26, 26, 26]],

        [[26, 26, 26],
         [26, 26, 26]]])

In [5]:
t2 = torch.tensor([
    [[11, 12, 13], 
     [13, 14, 15]], 
    [[15, 16, 17], 
     [17, 18, 19.]]])

# concat when shapes are compatible
t3 = torch.cat((t1,t2))
t3

tensor([[[26., 26., 26.],
         [26., 26., 26.]],

        [[26., 26., 26.],
         [26., 26., 26.]],

        [[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [10]:
t4 = torch.tensor([[1,1,2],[21,0,9]])
t4.shape

torch.Size([2, 3])

In [14]:
t5 = torch.transpose(t4,0,1)
t5

tensor([[ 1, 21],
        [ 1,  0],
        [ 2,  9]])